# Generated by Django 5.2.10 on 2026-01-08 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ROAD', 'Road & Transportation'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Sanitation'), ('STREET_LIGHT', 'Street Light'), ('DRAINAGE', 'Drainage'), ('GARBAGE', 'Garbage Collection'), ('TRAFFIC', 'Traffic Management')], max_length=50)),
                ('description', models.TextField()),
                ('citizen_image', models.ImageField(blank=True, null=True, upload_to='citizen_issues/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SOLVED', 'Solved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_image', models.ImageField(upload_to='solutions/')),
                ('remarks', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ROAD', 'Road & Transportation'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Sanitation'), ('STREET_LIGHT', 'Street Light'), ('DRAINAGE', 'Drainage'), ('GARBAGE', 'Garbage Collection'), ('TRAFFIC', 'Traffic Management')], max_length=50)),
                ('role', models.CharField(choices=[('FIELD', 'Field Officer'), ('HEAD', 'Department Head')], max_length=10)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.officer'),
        ),
    ]
