# Generated by Django 5.2.10 on 2026-01-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_officer',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='citizen_image',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='role',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SOLVED', 'Solved')], default='REPORTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='category',
            field=models.CharField(choices=[('ROAD', 'Road & Transportation'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Sanitation')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
        ),
        migrations.DeleteModel(
            name='IssueResolution',
        ),
    ]
