# Generated by Django 5.2.11 on 2026-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('ROAD', 'Road'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Sanitation'), ('ENVIRONMENT', 'Environment'), ('SAFETY', 'Safety'), ('STREET_LIGHT', 'Street Light'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
