# Generated by Django 5.2.11 on 2026-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HEAD', 'Head - All Categories'), ('ROAD', 'Road'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Sanitation'), ('ENVIRONMENT', 'Environment'), ('SAFETY', 'Safety'), ('STREET_LIGHT', 'Street Light'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('head', 'Head')], default='officer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
