# Generated by Django 5.2.10 on 2026-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='solver_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='solver_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='solver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='work_done',
            field=models.TextField(blank=True, null=True),
        ),
    ]
