# Generated by Django 5.2.10 on 2026-01-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='Untitled Issue', max_length=200),
            preserve_default=False,
        ),
    ]
