# Generated by Django 5.2.10 on 2026-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_resolution_date_issue_solver_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_officer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_officer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='designation',
            field=models.CharField(default='Field Officer', max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('officer', 'Officer'), ('dept_head', 'Department Head'), ('head', 'Overall Head')], default='officer', max_length=20),
        ),
    ]
