# Generated by Django 5.2.11 on 2026-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_assigned_officer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category_issue_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='display_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
