class AppStrings {
  static const Map<String, Map<String, String>> _localized = {
    "en": {
      "app_name": "SmartServe",
      "select_language": "Select Language",
      "welcome": "Welcome to SmartServe",
      "tagline": "Your voice, Our action",
      "report": "Report",
      "dashboard": "Dashboard",
      "my_issues": "My Issues",
      "notifications": "Notifications",
      "report_issue": "Report Issue",
      "name": "Full Name",
      "mobile": "Mobile Number",
      "title": "Issue Title",
      "description": "Description",
      "location": "Location",
      "select_category": "Select Category",
      "submit": "Submit Issue",
      "select_map": "Pick Location on Map",
      "photo": "Add Photo",
      "total": "Total",
      "reported": "Reported",
      "in_progress": "In Progress",
      "completed": "Completed",
      "no_issues": "No issues found",
      "issue_submitted": "Issue submitted successfully!",
      "issue_error": "Failed to submit. Try again.",
      "loading": "Loading...",
      "road": "Road",
      "water": "Water",
      "electricity": "Electricity",
      "sanitation": "Sanitation",
      "environment": "Environment",
      "safety": "Safety",
      "street_light": "Street Light",
      "other": "Other",
      "issue_details": "Issue Details",
      "officer_remarks": "Officer Remarks",
      "submitted_on": "Submitted on",
      "status": "Status",
      "no_notifications": "No notifications yet",
      "mark_read": "Mark as read",
      "save_mobile": "Enter your mobile to view issues",
      "mobile_hint": "10-digit mobile number",
    },
    "hi": {
      "app_name": "स्मार्टसर्व",
      "select_language": "भाषा चुनें",
      "welcome": "स्मार्टसर्व में आपका स्वागत है",
      "tagline": "आपकी आवाज़, हमारी कार्रवाई",
      "report": "रिपोर्ट",
      "dashboard": "डैशबोर्ड",
      "my_issues": "मेरी शिकायतें",
      "notifications": "सूचनाएं",
      "report_issue": "शिकायत दर्ज करें",
      "name": "पूरा नाम",
      "mobile": "मोबाइल नंबर",
      "title": "समस्या शीर्षक",
      "description": "विवरण",
      "location": "स्थान",
      "select_category": "श्रेणी चुनें",
      "submit": "शिकायत जमा करें",
      "select_map": "नकशे पर स्थान चुनें",
      "photo": "फोटो जोड़ें",
      "total": "कुल",
      "reported": "दर्ज",
      "in_progress": "प्रगति में",
      "completed": "पूर्ण",
      "no_issues": "कोई शिकायत नहीं",
      "issue_submitted": "शिकायत सफलतापूर्वक दर्ज हुई!",
      "issue_error": "विफल। दोबारा प्रयास करें।",
      "loading": "लोड हो रहा है...",
      "road": "सड़क",
      "water": "पानी",
      "electricity": "बिजली",
      "sanitation": "स्वच्छता",
      "environment": "पर्यावरण",
      "safety": "सुरक्षा",
      "street_light": "स्ट्रीट लाइट",
      "other": "अन्य",
      "issue_details": "शिकायत विवरण",
      "officer_remarks": "अधिकारी टिप्पणी",
      "submitted_on": "दर्ज तिथि",
      "status": "स्थिति",
      "no_notifications": "अभी कोई सूचना नहीं",
      "mark_read": "पढ़ा हुआ मार्क करें",
      "save_mobile": "शिकायतें देखने के लिए मोबाइल दर्ज करें",
      "mobile_hint": "10 अंकों का मोबाइल नंबर",
    },
    "mr": {
      "app_name": "स्मार्टसर्व",
      "select_language": "भाषा निवडा",
      "welcome": "स्मार्टसर्वमध्ये आपले स्वागत",
      "tagline": "तुमचा आवाज, आमची कृती",
      "report": "तक्रार",
      "dashboard": "डॅशबोर्ड",
      "my_issues": "माझ्या तक्रारी",
      "notifications": "सूचना",
      "report_issue": "तक्रार नोंदवा",
      "name": "पूर्ण नाव",
      "mobile": "मोबाईल नंबर",
      "title": "समस्या शीर्षक",
      "description": "वर्णन",
      "location": "स्थान",
      "select_category": "श्रेणी निवडा",
      "submit": "तक्रार सादर करा",
      "select_map": "नकाशावर स्थान निवडा",
      "photo": "फोटो जोडा",
      "total": "एकूण",
      "reported": "नोंदवले",
      "in_progress": "प्रगतीत",
      "completed": "पूर्ण",
      "no_issues": "कोणत्याही तक्रारी नाहीत",
      "issue_submitted": "तक्रार यशस्वीरित्या सादर झाली!",
      "issue_error": "अयशस्वी. पुन्हा प्रयत्न करा.",
      "loading": "लोड होत आहे...",
      "road": "रस्ता",
      "water": "पाणी",
      "electricity": "वीज",
      "sanitation": "स्वच्छता",
      "environment": "पर्यावरण",
      "safety": "सुरक्षा",
      "street_light": "रस्त्यावरील दिवे",
      "other": "इतर",
      "issue_details": "तक्रार तपशील",
      "officer_remarks": "अधिकारी टिप्पणी",
      "submitted_on": "सादर तारीख",
      "status": "स्थिती",
      "no_notifications": "अजून सूचना नाहीत",
      "mark_read": "वाचले म्हणून चिन्हांकित करा",
      "save_mobile": "तक्रारी पाहण्यासाठी मोबाईल प्रविष्ट करा",
      "mobile_hint": "10 अंकी मोबाईल नंबर",
    },
  };

  static String text(String key, String lang) {
    return _localized[lang]?[key] ?? _localized['en']?[key] ?? key;
  }
}